### ISSUE TITLE
Rocks and Minerals

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#1]
**This will replace the current rocks and minerals page**
https://geology.utah.gov/popular/general-geology/rocks-and-minerals/

Preview Link: https://geology.utah.gov/?page_id=50455&preview=1&_ppp=e053e5bbd1

**Comment by marshallrobinson** [comment]
Looks great overall. A couple comments:

- [ ] Minerals accordion: change "80 to100" to "80 to 100"
- [ ] Rocks accordion: not sure if "What are Igneous, Sedimentary, & Metamorphic Rocks" needs to be italicized? (I think it just throws me off because of the "?" at the end of the webpage title in a sentence.

**Comment by Mackenzie-Cope** [comment]
Mike Hylland's Comments

- USGS hyperlink under Rocks vs. Minerals: I recently had a USGS Bureau Approving Officer tell me that they never spell out "United States" when they spell out "Geological Survey" (i.e., they use "U.S. Geological Survey). I recommend we do the same.
- "Rocks" info box, 1st line: Recommend italicizing Rock and rocca (convention used for words that refer to themselves). Same for Mineral and mineralis in the first line of the "Minerals" info box.
- "Rocks" info box, 2nd paragraph: Insert "and" before "chocolate chips" (...butter, and chocolate chips are the minerals...).
- Rock, Mineral, and Fossil Collecting, last sentence: I think "Recorder's Office" should be capitalized.
- "Artifacts" description, 1st sentence: Change "is" to "are" (...that are more than...).

**Comment by Mackenzie-Cope** [comment]
**1. fixed to U.S. Geological Survey
2. fixed italics
3. added and
4. capitalized recorders office
5. changed is to are**
