### ISSUE TITLE
Wetland Stream and Permit Data webpage- need data update

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#104]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/wetlands-on-private-land/wetland-stream-permit-data/

### Describe the change(s) you would like to request.

All of the files on the webpage need to be updated to the latest files, which can all be found here: U:\GWP\Wetland\GIS\uilf_in_lieu_fee\permit_processing_data\most_recent_data. Additionally, we need to add in the link to the Mitigation Program Study. That link is here: https://doi.org/10.34191/OFR-756

### How Urgent is this?

Medium

### If high urgency, please explain.

Ideally should be done before the end of the fiscal year due to legislative requirement to post this information online.

### Additional notes

I am not sure what kind of review process any of the data need to go through. The Data Field Descriptions spreadsheet and Data Explanation docs initally went through the full UGS review process. I made some minor edits on both that Stephanie signed off on. No one has independently reviewed the project, impact and mitigation data. I am not sure if I need someone to review that data before posting.

**Comment by Mackenzie-Cope** [comment]
Files updated on server and page updated.
