### ISSUE TITLE
Multimedia & Downloads

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#11]
**This will replace the current Multimedia page**
https://geology.utah.gov/popular/multimedia/

Preview Link: https://geology.utah.gov/?page_id=50640&preview=1&_ppp=0d3efccf9b

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

Lake bonneville flood vimeo video opens in lightbox and then can't play unless you open in Vimeo. I can't find a way to fix that at the moment. The video plays just fine if you click through to Vimeo though. I'll add this to my future fix list.

Waiting on a hazards portal tile to replace the Q Faults app tile.

**Comment by marshallrobinson** [comment]
Page looks great, well done! One comment:

- [ ] The Water and Glaciers video says "Sorry Because of its privacy settings, this video cannot be played here" but then directs me to watch it on Vimeo. Is it possible to change the privacy settings so it can be "played here"?

**Comment by Mackenzie-Cope** [comment]
Unfortunately, the video is not ours and we can't change the privacy settings. Also, none of the "open in a new window" settings are working so for now I've added text under that vid "Click through message to watch video on Vimeo."

**Comment by mikehylland** [comment]
Looks good to me!
