### ISSUE TITLE
Teaching Kits

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#13]
**This will replace the current Teaching Kits page**
https://geology.utah.gov/teachers/teaching-kits/

Preview Link: https://geology.utah.gov/?page_id=51481&preview=1&_ppp=79c41cbeb4

**Comment by Mackenzie-Cope** [comment]
- Might not need the code anymore if that covid message is going to stay up. 

- We should get photos of the glacier model, globe, and stream table too.

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Love the new design and pictures. Well done! A couple suggestions:

- [ ] I was confused when reading "Contain" at the beginning of each teaching kit. It makes sense when beginning the sentence with the plural teaching kit, but my eye treated the teaching kit name as a title and the text underneath it as its own sentence. I suggest changing each teaching kit (and other check-out-able items) name to singular and "Contain" (or "Include") to <strong>"Contents:"</strong> (If this ends up not looking good, please don't do it :)..)
- [ ] Personal preference here, but I suggest a little more white-space between the titles and text on the "Stream Tables," "Glacier Model," and "Plate Tectonics Globe" elements.

**Comment by Mackenzie-Cope** [comment]
1. The old text was in more of a sentence/paragraph format and now its more like a title so I see what you mean. I've modified the formatting to a title and description with "Contains" to make more sense. Good catch, Marshall.
2. fixed the spacing issue. Using a "content slider" element instead of "testimonial"

**Comment by mikehylland** [comment]
Looks good to me!
