### ISSUE TITLE
Dinosaurs and Fossils

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#19]
**This will replace the current dinosaurs and fossils page**
https://geology.utah.gov/popular/general-geology/dinosaurs-fossils/

Preview Link: https://geology.utah.gov/?page_id=38004&preview=1&_ppp=b73786d8d6

**Comment by jackie-dewolfe** [comment]
I searched and tried to configure the buttons on the timeline, and couldn't seem to find where to change them. May need CSS, if possible.

**Comment by Mackenzie-Cope** [comment]
We need to add a link to the Utahraptor Megablock Project here.

**Comment by jackie-dewolfe** [comment]
Added section for the Megablock

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

DONE: added css for the nav buttons Jackie mentioned in a previous comment.
Needs two mobile-friendly banners. Sent to Jackie.

**Comment by marshallrobinson** [comment]
Looks great!

**Comment by Mackenzie-Cope** [comment]
Mike Hylland's Comments:

- Intro text, 3rd sentence: Delete "from the Cretaceous Period." These other types of fossils occur in the Triassic and Jurassic as well (e.g., petrified wood in the Triassic Chinle, crinoid columnals in the Jurassic Carmel, plants and bugs in the Jurassic Morrison, etc.).
- Intro text, 4th sentence: Consider adding something about "Paleozoic trilobites," since this text is introducing all types of fossils in Utah, tribolites are widely known, and we show a picture of them right below the intro text.
- Caption for "legjam" photo: There's a bit of redundancy with "Hanksville-Burpee Quarry" and "Wayne County" that could be cleaned up.
- Caption for trilobite photo: Italicize Elrathia kingii (genus and species names). Also note spelling of "kingii" (two i's at end).
- "Utah Dinosaurs" text: I'm confused by the second sentence, which implies that no dinos have been found/described from the Triassic. But the Dinos of Utah poster indicates 3 faunas from the Triassic Chinle. Is one or the other of these incorrect, or ? [I later saw a "no Triassic dinos discovered in Utah" comment in the Triassic section of the "Utah in the Age of Dinosaurs" page; perhaps the Dinos of Utah poster needs some clarification?]
- Saurischian and Ornithichian bullets: I'm thinking if we explain "herbivorous", we should also explain "carnivorous." And for the "herbivorous" explanation, maybe "plant-eating" would be better than "plant eaters"? (Similarly, "meat-eating" for "carnivorous.")
- In caption for Stikes reconstruction, "Utahraptor" should be plain text (i.e., genus name, but since the caption as a whole is italicized, the genus name shouldn't be).
- Fossils in Utah, 215 Ma panel: Change "flood plains" (2 words) to "floodplains" (1 word). Change "fresh-water" (two words, hyphenated) to "freshwater" (one word, no hyphen).
- Fossils in Utah, 200 Ma panel: Please check "Moenave Sandstone"; pretty sure it should be "Moenave Formation." Also, recommend using the official tracksite name (St. George Dinosaur Discovery Site at Johnson Farm) rather than "Johnson Farm's track site near St. George."
- Fossils in Utah, 170 Ma panel: Italicize Isocrinus (genus name).
- Fossils in Utah, 150 Ma panel: Italicize Allosaurus (genus name).
- Fossils in Utah, 1.8 Ma-15 ka panel: Change 1.8 to 2.6 (in both heading and first sentence). Also, the age range given for the Quaternary is a bit confusing, as we're still in the Quaternary Period (i.e., it didn't end 15,000 years ago). Seems preferable to refer to the Pleistocene Epoch instead, and give the age range as 2.6 mya - 12,000 ya. Finally, in last sentence, suggest changing "event" to "episode" (...latest glacial episode...).
- Megablock Project: Italicize Utahraptor (genus name) in heading and paragraph text.
- Tracks & Other Trace Fossils, caption for Navajo erg illustration: Italicize Brasilichnium (ichnogenus name).
- Tracks & Other Trace Fossils, caption for photo of Navajo block with tracks: There's a bit of redundancy with "Glen Canyon National Recreation Area" and "San Juan County" that could be cleaned up.
- Tracks & Tracksites drop-down text: In 2nd sentence, change "it" to "them" (...animals that made them). In 3rd sentence, consider changing "preserved well" to "well preserved" (...if they are well preserved).

**Comment by Mackenzie-Cope** [comment]
**1. deleted cretaceous period
2. added trilobites to last intro sentence
3. fixed redundancy caption
4. fixed trilobite photo caption**
5. Checking with Paleo section on poster clarification, etc.
**6. Fixed plant-eating and added meat-eating
7. Added italics in lightbox caption, can't do it in the auto-caption
8. Fixed floodplains and freshwater
9. fixed moenave formation and correct tracksite name
10. fixed170 Ma panel
11. fixed 150 Ma panel
12. changed quaternary language and dates to Pleistocene
13. italicized utahraptor
14. added italics in lightbox
15. fixed redundancy
16. fixed wording**

**Comment by Mackenzie-Cope** [comment]
Martha Hayden is working with me to update our Dinosaur information. She says the info on the pages may be 20 years old. Not sure if we will be doing major content updates (and sending through review again) now, or smaller updates after the pages are live. That will depend on the time availability of the paleo section.

For now, the Triassic Dinosaurs section has been updated with some info from Martha, addressing the fifth issue from Hylland.

**Comment by Mackenzie-Cope** [comment]
We have looped Don and Mark into the conversation. We have a few major updates that need to be made at some point, but Don said the content we have is sufficient for now and we can add to it later so we don't hold up all of Popular going live.

Closing this issue for now. We will be adding dino updates to the Website Changes Project moving forward.
