### ISSUE TITLE
Landforms

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#20]
**This will replace the current Utah Landforms page**
https://geology.utah.gov/popular/general-geology/utah-landforms/

Preview Link: https://geology.utah.gov/?page_id=38187&preview=1&_ppp=455f004d54

**Comment by Mackenzie-Cope** [comment]
- [ ] All Links Checked
 - [x] Design Uniformity
 - [ ] Mobile Accessibility
 - [ ] Photo Captions
 - [ ] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Looks great overall. One comment:

- [ ] Plateau image #3 caption: Change "rocks.Fishlake" to "rocks. Fishlake"

**Comment by mikehylland** [comment]
- Intro text, 1st paragraph, last sentence: Insert comma after "example" (...for example, a single earthquake...).
- Intro text, 3rd paragraph: Delete the comma immediately before "and volcanic activity" (...[1.2 meters]) and volcanic activity...).
- Intro text, last paragraph: Consider replacing "stretching" with "extension." Also, change "rock falls" (2 words) to "rockfalls" (1 word).
- Mountains gallery, photo 1: Address redundant content in caption.
- Mountains gallery, photo 2: Insert space after first sentence and before "A". Also delete redundant location info at end of caption.
- Mountains gallery, photos 3-5: No photographer info?
- Glaciers gallery, photo 1: Perhaps the caption should say something about glaciers (e.g., glacial valley)? Photographer info?
- Volcanoes gallery, photos 2-4: No photographer info?
- Volcanoes, Definitions: In "Crater" definition, delete "-shaped" (A circular depression...). Might be helpful to add a definition for "caldera," as many might not grasp the difference between a caldera and a crater.
