### ISSUE TITLE
Geologic History

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#21]
**This will replace the current Geologic History, Utah: A Geologic History, and Utah's geologic history pages**
https://geology.utah.gov/popular/general-geology/geologic-history/
http://geology.utah.gov/popular-geology/general-geology/geologic-history/utah-a-geologic-history/
https://geology.utah.gov/popular/general-geology/geologic-history/utahs-geologic-history/

Preview Link: https://geology.utah.gov/?page_id=51687&preview=1&_ppp=d7b4bf79a0

**Comment by Mackenzie-Cope** [comment]
- [ ] All Links Checked
 - [ ] Design Uniformity
 - [ ] Mobile Accessibility
 - [ ] Photo Captions
 - [x] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Looks good to me, great work!

**Comment by mikehylland** [comment]
- Caption for badlands photo: "On top of the sandstone" lacks context (i.e., there's no prior mention of "the sandstone"). Is there a previous sentence that's gone missing, or? If the current caption is all we have to work with, it would probably be fine to simple delete "on top of the sandstone."
- Sentence beginning, "We don't know as much...": Recommend adding "of Utah's geologic history" after "3 billion years" (...first 3 billion years of Utah's geologic history as we know about...).
- In that same sentence, change "Paleozoic Era" to "Phanerozoic Eon" (i.e., 540-million-year duration = Paleozoic + Mesozoic + Cenozoic).
- Last sentence of text before the timeline: Delete "and" from before "igneous" (...metamorphism, igneous intrusion, erosion...).
- In the panels for the timeline, there are quite a few boundary ages that should be updated; several differ by up to several million years from current time scales (e.g., GSA, ICS, etc.), notably the Quaternary (starting at 2.6 Ma vs. 1.8 Ma on the timeline).
- Maybe it's just in my desktop view, but there appears to be a text wrapping issue in timeline panel no. 1(?) (i.e., narrow column of text down the right side of the panel).
- Text in timeline panel no. 10, 2nd sentence: Add a comma after "Plateau" (...Colorado Plateau, why much of the Basin and Range...).
- In the expanded tabs for CZ, MZ, and PZ, similar comment as above re: differences in boundary ages between the old PI-19 and current geologic time scales. The old publications are what they are, but I think the interactive web page info needs to be up to date.

**Comment by Mackenzie-Cope** [comment]
**1. fixed caption
2. added geologic history bit
3. fixed phanerozoic
4. deleted "and"**
5. working on updating time scale ranges
**6. fixed wrapping issue
7. added comma**
8. updating time scale ranges
