### ISSUE TITLE
Popular Geology Main

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#22]
**This will replace the Popular Geology, general geology, and places to go pages**
https://geology.utah.gov/popular/

Preview Link: https://geology.utah.gov/?page_id=50564&preview=1&_ppp=fe096c268f

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [ ] Mobile Accessibility
 - [ ] Photo Captions
 - [x] SLM Correct (and mobile)

General Note: We should take another look at the mobile/tablet versions at a later date, website-wide. The flip boxes only look correct and "flip" on desktop.

**Comment by marshallrobinson** [comment]
Looks great, just one comment:
- [ ] Copper caption: change "of both electricity an heat" to "of both electricity and heat"

**Comment by mikehylland** [comment]
- In the intro paragraph, 3rd sentence, consider adding "plateaus" to the list of Utah geographic features (The diverse mountain ranges, basins, and plateaus in Utah were formed...).
- For the Great Salt Lake "rock hammer link," recommend adding "& Lake Bonneville" (same as the link title in the list on the left side of the page).
- In the pop-up text for the Geologic History "rock hammer link," recommend adding a "from" and a "the" (...Utah's changing environment from 540 million years ago to the present).
- In the pop-up text for the Ice Age "rock hammer link," we should change "about 3 million years ago" to "about 2.6 million years ago." Rounding to the nearest million years is too coarse for the Quaternary, and puts the beginning of the Ice Age in the Pliocene (confusing).
- In the pop-up text for the Earthquakes, Landslides, & Other Hazards "rock hammer link," delete the colon after "including."
- Coal description, 2nd sentence: Change "covert" to "convert" (...and convert it to peat...).
- Honeycomb calcite description: The age of the stone is incorrect (i.e., not "more than 500 million years old"). The host rock is Mississippian (~350 Ma), and the alteration that formed the honeycomb calcite occurred ~40-15 Ma. The 500 Ma age was reported in error in a news piece; the correct age info is included in the honeycomb calcite description in our 2022 Calendar of Utah Geology.
- State Fossil description: Italicize _Allosaurus_ and _Tyrannosaurus rex_ (genus & species names).
- State Dinosaur description: Italicize _Utahraptor_ and _Velociraptor_ (genus names).
- State Work of Land Art description: We have to include copyright language anytime we use an image of the Spiral Jetty (yep, even if it's one of our own photos; the copyright is for the artwork itself). Jen can provide the appropriate language.

**Comment by Mackenzie-Cope** [comment]
**1. added plateaus
2. added lake bonneville
3. added from and the
4. changed 3 to 2.6
5. removed colon
6. fixed convert
7. fixed honeycomb calcite description
8. fixed italics
9. fixed italics**
10. working on spiral jetty language
