### ISSUE TITLE
Utah in the age of dinosaurs

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#28]
**This will replace the Utah in the age of dinosaurs page and the lower pages of Jurassic, Early Cretaceous, and Late Cretaceous Dinosaurs. The new page will be a combination of all these pages.**
https://geology.utah.gov/popular/general-geology/dinosaurs-fossils/age-of-dinosaurs/
https://geology.utah.gov/popular/general-geology/dinosaurs-fossils/age-of-dinosaurs/early-cretaceous-dinosaurs-of-utah/
https://geology.utah.gov/popular/general-geology/dinosaurs-fossils/age-of-dinosaurs/late-cretaceous-dinosaurs-of-utah/
https://geology.utah.gov/popular/general-geology/dinosaurs-fossils/age-of-dinosaurs/jurassic-dinosaurs-of-utah

Preview Link: https://geology.utah.gov/?page_id=52982&preview=1&_ppp=a7a04e9d25

**Comment by jackie-dewolfe** [comment]
Added ESW text to this page, didn't change anything in the specific dino AWSM widgets.

**Comment by Mackenzie-Cope** [comment]
I wonder if we should change the formatting for the dinos? On mobile (and desktop without hovering) you can't see any dino names, only images. Maybe the AWSM Team plugin is too locked-down for these? IDK

**Comment by jackie-dewolfe** [comment]
I changed the layout on this plug-in to a list, it's a little longer, but it looks better in mobile and you can see what each illustration/dino is.

**Comment by Mackenzie-Cope** [comment]
- [ ] All Links Checked
 - [x] Design Uniformity
 - [ ] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Looks great overall. One suggestion:

- [ ] Sauropelta: Change "very largest" to say "largest"

**Comment by mikehylland** [comment]
- Please check the Triassic, Jurassic, and Cretaceous boundary ages for conformance with current geologic time scales.
- For the listing of the three geologic periods making up the Mesozoic, consider listing them youngest to oldest. That would show them in a "stratigraphically correct" order and also be consistent with the order that they're presented in the section that follows. If the listing is re-ordered that way, it would make sense to also list the boundary ages for each period younger to older (e.g., 66 to 145 million years ago, etc.).
- In caption for Stikes reconstruction image, make "Utahraptor" plain text.
- Cretaceous Period text, 2nd paragraph, 3rd sentence: Change "further" to "farther" (Farther south in the ...).
- Animantarx paragraph: Middle of paragraph has numerous grammatical issues. Please replace with the following (in particular, note hyphenation, capitalization, commas, and quote marks; changes indicated by bold):

He performed a detailed survey of the **low-level** radiation levels across the area as he knew the bones there were slightly radioactive. Finding a spot that was slightly radioactive, he **said, "Dig here," and, lo and behold, the** first dinosaur ever discovered solely by technology was found.

- Eolambia paragraph, 3rd sentence: Change "it's" (with apostrophe -- i.e., contraction of "it is") with "its" (no apostrophe -- i.e., possessive) (Its direct ancestors...).
- Gastonia paragraph: 2nd sentence, change "cover" to "covered" (...body covered by armor...). 4th sentence, italicize _Utahraptor_. Last sentence, capitalize "age" (...the Age of Ankylosaurs).
- Iguanodon paragraph, last sentence: Add "National Park" after "Arches."
- Nedcolbertia paragraph: 1st sentence, add commas after "small" and "built" (...a small, lightly built, predatory dinosaur). 2nd sentence, add "National Park" after "Arches." 3rd sentence, replace the comma after "Utah" with a semicolon (...only known in Utah; however, scientists...).
- Pleurocoelus paragraph: 3rd sentence, italicize _Pleurocoelus_. 4th sentence, add comma after "Formation" (...in the Cedar Mountain Formation, telling scientists...).
- Sauropelta paragraph, 1st sentence: Add a comma after "dinosaurs" (...armored dinosaurs, ranging up to...).
- Tenontosaurus paragraph: 2nd sentence, add commas after "ornithopods" and "feet" (Unlike other large ornithopods, this 1–2 ton beast had four toes on its hind feet, indicating that it is...).
- Utahraptor paragraph, 2nd sentence: Italicize _Velociraptor_.

**Comment by Mackenzie-Cope** [comment]
**1. updated time scale ranges for periods
2. reordered periods and time ranges
3. made Utahraptor plain text
4. fixed to farther
5. fixed animantarx
6. fixed eolambia
7. fixed gastonia
8. fixed iguanodon
9. fixed nedcolbertia
10. fixed pleurocoelus
11. fixed sauropelta
12. fixed tenontosaurus
13. fixed utahraptor
14. fixed torosaurus
15. fixed parasaurolophus
16. fixed struthiomimus
17. fixed troodon
18. fixed Jurassic image
19. fixed barosaurus
20. fixed brachiosaurus
21. fixed diplodocus
22. fixed photo caption**
