### ISSUE TITLE
Geothermal Resources

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#57]
Preview Link: https://geology.utah.gov/?page_id=46753

Replaces this page: https://geology.utah.gov/resources/energy/geothermal/

**Comment by jackie-dewolfe** [comment]
All addressed but the last comment.

**Comment by Mackenzie-Cope** [comment]
Looks good,
I added a FORGE tab section that links to the FORGE site and MP-169. 
I also added MP-169 to the highlighted pubs section at the bottom.
