### ISSUE TITLE
Energy & Mineral Statistics

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#61]
Preview Link: https://geology.utah.gov/?page_id=46260

Replaces this page: https://geology.utah.gov/resources/energy/utah-energy-and-mineral-statistics/

**Comment by Mackenzie-Cope** [comment]
I replaced this whole table with the most recent version on the live page. MH's comments are addressed on the most recent version.

**Comment by jackie-dewolfe** [comment]
Good here.
