### ISSUE TITLE
Energy & Minerals Main

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#63]
Preview Link: https://geology.utah.gov/?page_id=55978

Replaces this page: https://geology.utah.gov/resources/energy/

**Comment by Mackenzie-Cope** [comment]
Sent an email to Steph about adding critical minerals.

Addressed carbon seq. pop-up.

**Comment by jackie-dewolfe** [comment]
Waiting on Steph for crit. minerals bit? Otherwise looks good!

**Comment by Mackenzie-Cope** [comment]
Steph got back to me and we're leaving it out of the paragraph. She said it's covered enough with the mention of industrial minerals and metals.
