### ISSUE TITLE
Carbon Sequestration

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#65]
Preview Link: https://geology.utah.gov/?page_id=46831

Replaces this page: https://geology.utah.gov/resources/energy/carbon-sequestration/

**Comment by Mackenzie-Cope** [comment]
Addressed carbon seq. project contact.

Also changed the giant button to a promo box/icon box combo.

**Comment by jackie-dewolfe** [comment]
All looks good!
