### ISSUE TITLE
Coal

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#66]
Preview Link: https://geology.utah.gov/?page_id=46234

Replaces this page: https://geology.utah.gov/resources/energy/coal-coalbed-methane/

**Comment by jackie-dewolfe** [comment]
Second comment addressed, first may need to ask EMP?

**Comment by Mackenzie-Cope** [comment]
Did some research on the Grand Staircase comment. Biden hasn't officially announced the re-enlargement so we'll wait until he does and then change the webpages as necessary.
