### ISSUE TITLE
Oil Shale

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#70]
Preview Link: https://geology.utah.gov/?page_id=46881

Replaces this page: https://geology.utah.gov/resources/energy/oil-shale/

**Comment by jackie-dewolfe** [comment]
**Addressed**- Intro paragraph, first sentence: Not sure about the “particles of other minerals” at the end of the sentence, as no other minerals besides these have been mentioned (i.e., other than what?). Consider something like, “clay- and silt-sized sediment grains.”

_Oil shale example with scale?_ - Nice photo of the oil shale sample, but something for scale would be helpful.

Again, great “presentation” of the Presentations, Posters, etc. (all the needed info for reference citations appears to be provided).

**Comment by Mackenzie-Cope** [comment]
Looks good.
