### ISSUE TITLE
Coalbed Methane

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#71]
Preview Link: https://geology.utah.gov/?page_id=46732

Replaces this page: https://geology.utah.gov/resources/energy/coal-coalbed-methane/coalbed-methane-plays/

**Comment by Mackenzie-Cope** [comment]
Fixed the wording from a previous comment.

I took the photos out. I don't of any photos that are better suited for this page.

I reached out to Jeff Quick about the plays content. If this content isn't up-to-date, we should keep this page a draft and make a plan to come up with new content and a new page with EMP in the future.

I added authors on these poster presentations.

**Comment by Mackenzie-Cope** [comment]
I took out the plays content that was time-specific. Jeff got back to me and said the potential is still there, but not any development so I took out the development details that may be out of date.

**Comment by jackie-dewolfe** [comment]
This looks good to me.
