### ISSUE TITLE
Natural Gas

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#72]
Preview Link: https://geology.utah.gov/?page_id=46088

This is a new page.

**Comment by jackie-dewolfe** [comment]
**Addressed**- Intro paragraph, last sentence: Consider changing “residential uses” to “residential purposes” (to avoid “used for uses”). Also, after “uses” (purposes), change the existing comma to a semicolon (...used for residential purposes; however, natural gas-fired power plants…).

**Addressed**- Tight Gas Sands, middle of paragraph: Add “rocks” after “carbonate” (...sandstone, carbonate rocks…).

**Addressed**- Shale Gas, second sentence: Recommend adding a comma after “formations” (...into other formations, but have not…). Also, no hyphen in “in situ.”

**Addressed**- In the caption for the Cane Creek drilling diagram, recommend changing “level” to “flat-lying.”

**Addressed but see comment** (Second comment about CBM wording hasn't been addressed)- Coalbed Methane: Change “in contrast from” to “in contrast to.” Also, it’s unclear to me what it means to say that the CBM is stored “within the surface of the coal”; this wording may need revision.

**Good suggestion, is this possible though?**- Natural Gas Resources, Posters, and Presentations: I like how this section provides info on when and where the posters were presented, and by whom. Perhaps this convention can be used on other pages where this info is currently not given?

**Comment by Mackenzie-Cope** [comment]
CBM description stays the same for now. I found a few other descriptions on gov websites and they all have similar wording.

I'll make a note of the presentations display suggestion. We can take a look at after EMP is live.
