### ISSUE TITLE
Suggested changes to main UGS home page

### ISSUE THREAD

**Issue by Vandenberg5** [UGS-GIO/Website#79]
### On what web page are you requesting a change?

https://geology.utah.gov/

### Describe the change(s) you would like to request.

1) In the pop-up window for "Energy & Minerals", under quick links, can you remove "Core Center News" and add "Critical Minerals of Utah" between the mining report and UCRC links.

2) The "Energy" button in the center of the UGS main page used to go to the Energy and Mineral Statistics page, but this seems to have been changed and now links to the E&M main website.  Can the button be again linked to the Energy and Mineral Statistics website, and can the button be changed to say "Energy Statistics"

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
1. Quick links in menu, removed core center news and added critical minerals of utah.
2. Changed "energy" button on homepage to link to stats.

We're checking if we have the old image files for the homepage buttons to possibly change the wording

**Comment by Mackenzie-Cope** [comment]
We don't have the old button image files so it wouldn't be a quick change. We're going to leave the "energy" button as-is and linking to stats for now and I'm making a note of it for when we redo the homepage in 2022.
