### ISSUE TITLE
Suggested changes to Energy & Minerals main page

### ISSUE THREAD

**Issue by Vandenberg5** [UGS-GIO/Website#80]
### On what web page are you requesting a change?

https://geology.utah.gov/energy-minerals/

### Describe the change(s) you would like to request.

Towards the bottom of the page, under "Energy News", can the featured article be the most recently published, in this case it would be an article on Geothermal from Sept 2021.  Same for the Core Center News, can this location always show the most recent article?

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
These sections are set up to show the most recent articles. The latest energy news article was missing the category but I added it in. 

@jackie-dewolfe I've made a note in our cheat sheet to remember to add the categories when we make those pages.
