### ISSUE TITLE
Energy and Minerals main page, text changes

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Website#81]
### On what web page are you requesting a change?

https://geology.utah.gov/energy-minerals/

### Describe the change(s) you would like to request.

Let me start by saying that overall the page looks great! Thank you!

-In the caption of the photo of evaporation ponds - It should be "Compass Minerals' potash evaporation ponds..." instead of "Great Salt Lake Mineral's potash evaporation ponds..."

-Stephanie will probably want additional changes, but in the short term the text that pops up under "metals" should remove reference to lead and zinc. Utah is currently not mining those.

-In the main heading, please change the following sentence: "The state also has over 180 mining districts that produce a variety of base and precious metals, industrial minerals, and uranium." to "The state also has extensive mineral resources that contain a variety of base and precious metals, industrial minerals, and uranium. Several metallic and industrial mineral commodities are currently being produced, including copper, gold, limestone, potash, and salt."

-The text that pops up for IMs should be changed to read, "Industrial minerals in Utah are mined for several uses including construction materials, ingredients in commercial goods, and fertilizers. These types of resources are generally not considered fuels or metals."

### How Urgent is this?

Medium

**Comment by Mackenzie-Cope** [comment]
1. **done:** caption on ponds photo fixed.
2. We do have some descriptions of lead and zinc on the metals page from the content Steph gave us. I'll bring this up with Steph and see what she wants to do about that text. 
3. **done:** updated intro text with suggestions.
4. **done:** Changed text on IM flip box

**Comment by Mackenzie-Cope** [comment]
2. **done:** worked with Stephanie to change the wording there.
