### ISSUE TITLE
Industrial minerals page, various changes

### ISSUE THREAD

**Issue by arupke** [UGS-GIO/Website#82]
### On what web page are you requesting a change?

https://geology.utah.gov/energy-minerals/industrial-minerals/

### Describe the change(s) you would like to request.

-Remove the geochronology database web map link under the "Industrial Mineral Resources" heading.

-Under both the high-calcium limestone and high-magnesium dolomite headings, please add the following links for OFR 715:
https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-715/ofr-715.pdf
https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-715/ofr-715.zip

-We recently had a meeting with American Gilsonite and we're trying to respond to their requests in how we refer to Gilsonite in our publications, etc. (1) So, for the "Gilsonite" heading, let's change it to "Uintaite (Gilsonite)". (2) And for the corresponding text please modify to: "Uintaite (commonly referred to as Gilsonite) is a rare, solid hydrocarbon used in diverse applications such as asphalt paving mixes, coatings, ink, paint, and as a drilling fluid additive. Utah is the only state that produces uintaite." (3) In the header text for the IM page, please change "gilsonite" to "uintaite (Gilsonite)". If you can, insert the registered trademark symbol (R inside of a little circle) after Gilsonite in each occurrence.

-For highlighted scientific publications, let's remove OFRs 714, 727, 728. Those are more just general GSL-related publications. You could add OFR 715, SS 141, and OFR 600.

### How Urgent is this?

Medium

**Comment by Mackenzie-Cope** [comment]
1. **done**: removed geochron database
2. **done**: added ofr-715 to both
3. **done**: changed title to uintaite (gilsonite), changed description text to your suggestion, changed intro text reference to uintaite (gilsonite), and added registered trademark superscript to gilsonite references.
4. **done**: removed ofr 714, 727, 728. added ofr 715, ss-141, ofr-600
