### ISSUE TITLE
Geologic Mapping page, Keilee Higgs job title change, and move Grant Mauk to G&W page

### ISSUE THREAD

**Issue by KeileeAnn** [UGS-GIO/Website#85]
### On what web page are you requesting a change?

https://geology.utah.gov/about-us/mapping-program/

### Describe the change(s) you would like to request.

Keilee Higgs job title - GIS Geological Technician, not GIS Analyst. Also, looks like Grant Mauk was supposed to be on the Groundwater and Wetlands page, not the Geologic Mapping page! 

### How Urgent is this?

Low

### Additional notes

The website is amazing and I love it - I use it every single day for lots of different reasons! You've all done amazing work. Thanks so much!

**Comment by Mackenzie-Cope** [comment]
Job title updated on Mapping Program page and Staff Directory list.
Grant Mauk removed from mapping, confirmed on Groundwater/Wetlands.

@KeileeAnn Thanks for your comments! :)

**Comment by KeileeAnn** [comment]
@Mackenzie-Cope That was fast ;) Awesome work, it looks amazing! Thanks a bunch!
