### ISSUE TITLE
Page Title, Requested change(s) (i.e. change content, change photos, add new section, etc.)

### ISSUE THREAD

**Issue by markmilli** [UGS-GIO/Website#86]
### On what web page are you requesting a change?

https://geology.utah.gov/map-pub/survey-notes/geosights/rozel-point-spiral-jetty/

### Describe the change(s) you would like to request.

The _August 1995_ link is dead. 
"Several past editions of Survey Notes have run GeoSights articles on the oil seeps found at the Rozel Point oil field ([September 2005](http://geology.utah.gov/?p=5461), [August 1995](http://geology.utah.gov/surveynotes/archives/snt27-3.pdf) [pdf]) and the Spiral..."

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
Fixed all SN article links to "https"
Fixed broken Aug 1997 SN issue link.

@markmilli Thanks! Links on this page are updated now.
