### ISSUE TITLE
Author's note

### ISSUE THREAD

**Issue by markmilli** [UGS-GIO/Website#87]
### On what web page are you requesting a change?

https://geology.utah.gov/map-pub/survey-notes/geosights/geosights-bingham-canyon-mine/

### Describe the change(s) you would like to request.

Please add an author's note that there is a new visitor center. More info here- https://www.riotinto.com/operations/us/kennecott/visitor-experience

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
@markmilli I've added an author's note to this SN article. Take a look and let me know if you have any wording changes.

Also, do we want to hide the old overlook location information at the bottom of the page because it's out of date?

**Comment by markmilli** [comment]
I think the note is good.

Leave it. The overlook described in the article should still be accessible
and provides a totally different perspective. It is still worth the trip
up.

Mark


Mark Milligan, P.G.
Senior Geologist
Geologic Information and Outreach Program Manager
Utah Geological Survey
(801) 537-3326
***@***.***
geology.utah.gov
