### ISSUE TITLE
Mapping Program - Keilee Higgs Job Title change...again...

### ISSUE THREAD

**Issue by KeileeAnn** [UGS-GIO/Website#88]
### On what web page are you requesting a change?

https://geology.utah.gov/about-us/mapping-program/

### Describe the change(s) you would like to request.

Hi, I am the MOST annoying for this, but I just got promoted to Geologist (yay!) like literally 2 days after I asked you to change my job title from GIS Analyst to Geotech...so could you please change it again to Geologist? Sorry for the bad timing but it was a surprise to me, too. Thanks so much for your help again!

### How Urgent is this?

Low

### Additional notes

I APPRECIATE YOU GUYS AND OUR LOVELY WEBSITE

**Comment by Mackenzie-Cope** [comment]
Updated job title to geologist on Mapping page and Directory.

@KeileeAnn congrats! And no problem, it's an easy fix! :)

**Comment by KeileeAnn** [comment]
@Mackenzie-Cope thanks so much again!
