### ISSUE TITLE
Earth Science Week

### ISSUE THREAD

**Issue by Mackenzie-Cope** [UGS-GIO/Website#9]
**This will replace the current ESW page**
https://geology.utah.gov/teachers/earth-science-week/

Preview Link: https://geology.utah.gov/?page_id=51460&preview=1&_ppp=923f29990b

**Comment by Mackenzie-Cope** [comment]
- [x] All Links Checked
 - [x] Design Uniformity
 - [x] Mobile Accessibility
 - [x] Photo Captions
 - [x] Mobile SLM Correct

**Comment by marshallrobinson** [comment]
Page looks great, good work!

**Comment by mikehylland** [comment]
For the description of the "earthquake demonstrations," I wonder about shifting emphasis away from seismic hazards. How about something like:
- the **earthquake demonstrations** where the students discover where and how earthquakes happen and create their own earthquake while learning about earthquake safety

Maybe something to run past Mark M?

**Comment by Mackenzie-Cope** [comment]
I think this wording change is just fine. I have made the update.
