### ISSUE TITLE
Page Title, Requested change(s) (i.e. change content, change photos, add new section, etc.)

### ISSUE THREAD

**Issue by markmilli** [UGS-GIO/Website#90]
### On what web page are you requesting a change?

https://geology.utah.gov/about-us/#toggle-id-5

### Describe the change(s) you would like to request.

Not sure this is prudent for the future of UGS but I am now our legislative liaison. Could you 
-add  "Legislative Liaison" after my name on the GIO staff directory?
-add my name as legislative liaison to the Admin section of the staff directory?
-change my bio on the about GIO page (added text is bold but should not be on the webpage):
...Current job duties include: **legislative liaison,** preparing geologic brochures and booklets for the public, responding to public inquiries, writing articles for the UGS’s Survey Notes, creating geologic signage for public display, responding to press inquiries, speaking to public groups, and organizing and leading geologic field trips.

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
- Added legislative liaison to GIO directory for Mark (About UGS)
- Added Mark to Admin directory list as legislative liaison (About UGS)
- Added legislative liaison to Mark's AWSM Team description (GIO Page)

@markmilli This has been updated, thanks! The only thing I didn't add Legislative Liaison to was your title on the GIO page, do you want your job title to say "Geologic Manager | Legislative Liaison" here as well: https://geology.utah.gov/about-us/geologic-information-outreach-program/ ?
