### ISSUE TITLE
Wetland Main page, update to highlighted scientific publications

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#91]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/

### Describe the change(s) you would like to request.

Update the highlighted scientific publications section to highlight the following pubs

Updated Wetland Mapping in Cache County - [Download](https://ugspub.nr.utah.gov/publications/circular/c-133.pdf)
Cache Valley Wetland Mapping: Supplemental Report - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-744.pdf)
Central Basin and Range Ecoregion Wetland Assessment and Landscape Analysis - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-738/ofr-738.pdf)
Trait Data for Utah’s Central Basin and Range Wetland Plants - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-740.pdf)
Snake Valley Hydrologic Monitoring: Ten-Year Report - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-732.pdf)
Wetland conditions of the Weber River watershed - [Download](https://ugspub.nr.utah.gov/publications/public_information/pi-99.pdf)

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
Pubs have been updated. Other changes listed below. 

@wetlandsDiane The order of pubs was switched around a little for tablet and mobile spacing. If the order of pubs is an issue, let me know. I'll leave this issue open for the GeoData link addition.

Mobile optimizations, etc.:

- [x] Optimized the gallery for mobile
- [x] Tiles/items optimized for mobile
- [x] Promo box (pubs/articles box) optimized for mobile (tech pubs spacing, view all pubs button, public interest article table)
- [ ] New Utah Wetlands banner for mobile
- [ ] New Plant Portal banner for mobile
- [ ] Added GeoData link

**Comment by Mackenzie-Cope** [comment]
All changes are live!
