### ISSUE TITLE
Wetlands in Utah, update links and update highlighted pubs

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#92]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/wetlands-in-utah/

### Describe the change(s) you would like to request.

Update the highlighted scientific pubs to the following:

Updated Wetland Mapping in Cache County - [Download](https://ugspub.nr.utah.gov/publications/circular/c-133.pdf)
Cache Valley Wetland Mapping: Supplemental Report - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-744.pdf)
Utah Wetland Functional Classification: Version 1 Open-File report 661 (already listed)
Prioritizing Wetlands for Conservation in the Upper Bear River Watershed (already listed)
Great Salt lake Wetland Geomorphology (already listed, capitalize “lake” to “Lake”)
Wetland conditions of the Weber River watershed - [Download](https://ugspub.nr.utah.gov/publications/public_information/pi-99.pdf)

Under the Wetlands Mapping sectoin, in the last sentence, update the word "AGRC" to "UGRC." Keep the link the same.

Under the External Wetland Education Resources section, update the Bear River Migratory Bird Refuge link to https://fobrr.org/educational-reources/ 

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
- Updated highlighted pubs (again the order is slightly modified for spacing)
- Updated AGRC to UGRC
- Updated Bear River Refuge link

Mobile optimizations, etc.:

- [x] Optimized the gallery for mobile
- [x]  Promo box (pubs/articles box) optimized for mobile (tech pubs spacing, view all pubs button, public interest article table)
- [ ]  New Utah Wetlands banner for mobile
