### ISSUE TITLE
Wetlands- wildlife and plants, update pubs

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#93]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/wildlife-and-plants/

### Describe the change(s) you would like to request.

Update the list of highlighted sci pubs to the following:

Trait Data for Utah’s Central Basin and Range Wetland Plants - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-740.pdf)
Snake Valley Hydrologic Monitoring: Ten-Year Report - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-732.pdf)
Cache Valley Wetland Mapping: Supplemental Report - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-744.pdf)
Characterization of Boreal Toad Breeding Habitat in Utah (already listed)
Analysis of Landscape and Habitat Variables Associated with Boreal Toad (Anaxyrus boreas) Breeding Locations (already listed)
Characterizing Condition in At-Risk Wetlands of Western Utah: Phase I (already listed)

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
- updated pubs (no order changes necessary on this one)

Mobile optimizations, etc.: 

- [x] Optimized the gallery for mobile
- [x] Tiles/items optimized for mobile
- [x] Promo box (pubs/articles box) optimized for mobile (tech pubs spacing, view all pubs button, public interest article table)
- [ ] New Plant Portal banner for mobile
- [x] Added GeoData link
