### ISSUE TITLE
wetlands- health and restoration: updated highlighted pubs and some links

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#95]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/health-and-restoration/

### Describe the change(s) you would like to request.

Update highlighted sci pubs to the following:

Trait Data for Utah’s Central Basin and Range Wetland Plants - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-740.pdf)
Central Basin and Range Ecoregion Wetland Assessment and Landscape Analysis - [Download](https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-738/ofr-738.pdf)
Validation of a rapid wetland assessment protocol for Utah: testing inter-observer and intra-season variability - [Download](https://ugspub.nr.utah.gov/publications/reports_of_investigations/ri-278.pdf)
Validation of a rapid wetland assessment protocol for Utah: evaluation of survey methods and temporal and observer variability in vegetation data - [Download](https://ugspub.nr.utah.gov/publications/reports_of_investigations/ri-277.pdf)
Assessment of wetland condition and wetland mapping accuracy in Upper Blacks Fork and Smiths Fork, Uinta Mountains, Utah - [Download](https://ugspub.nr.utah.gov/publications/reports_of_investigations/ri-274.pdf)
Wetland conditions of the Weber River watershed - [Download](https://ugspub.nr.utah.gov/publications/public_information/pi-99.pdf)

Note that some of the above are already listed. Currently, the RI-278 incorrectly says "Variation of a Rapid Wetland Assessment Protocol" instead of Validation. Also, "wetland' should be capitalized in the title.

Under wetland assessment in the very last sentence, the link for the U.S. Forest Service should be updated to: https://www.fs.usda.gov/managing-land/natural-resources/geology/groundwater/groundwater-dependent-ecosystems#:~:text=What%20are%20Groundwater%20Dependent%20Ecosystems,and%20lakes%20are%20also%20included

Under Wetland Restoration, Creation, and Enhancement, and BMPs, last paragraph, update this sentence: The Association of State Wetland Managers](https://www.aswm.org/wetland-science/wetland-restoration) and the [Natural Resources Conservation Service](https://www.nrcs.usda.gov/wps/portal/nrcs/detail/national/water/wetlands/restore/?cid=nrcs143_010912) maintain web pages containing a wealth of information on a variety of topics related to restoration. to say this The [Association of State Wetland Managers](https://www.aswm.org/wetland-science/wetland-restoration) maintains a web page containing a wealth of information on a variety of topics related to restoration.

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
- updated pubs (no order change)
- Fixed titles to "validation" and fixed capitals
- updated Forest Service link to: https://www.fs.usda.gov/managing-land/natural-resources/geology/groundwater/groundwater-dependent-ecosystems
- Updated wetland restoration sentence. Although the hyperlink (https://www.aswm.org/wetland-science/wetland-restoration) does redirect to https://www.nawm.org/index.php @wetlandsDiane is there a specific page you want to link to or is the homepage ofr NAWM okay?

Mobile optimizations, etc.:

- [x] Optimized the gallery for mobile
- [x] Promo box (pubs/articles box) optimized for mobile (tech pubs spacing, view all pubs button, public interest article table)
- [x] Added GeoData link
