### ISSUE TITLE
Wildlife and Plants- change text in one section

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/Website#98]
### On what web page are you requesting a change?

https://geology.utah.gov/water/wetlands/wildlife-and-plants/

### Describe the change(s) you would like to request.

I want to update all of the text under the Sensitive Species section, including the title of the section, because the State changed rescinded the Sensitive Species statute and no longer has any species that are categorized as sensitive.

The proposed updated paragraph is below

Species in Need of Conservation Attention
Water diversions and associated alteration of aquatic habitats is the single most significant source of stress to Utah’s wildlife and habitat, according to the [Utah Wildlife Action Plan 2015-2025](https://wildlife.utah.gov/wildlife-action-plan.html) (UWAP). Accordingly, many of the plant and animal species in most need of conservation attention (as identified in the UWAP) are associated with aquatic features such as wetlands, streams, and riparian areas. Almost one-quarter of these animal species are wetland-dependent and an additional 39% depend on other aquatic habitats.
The UGS collaborates with partner agencies to collect and analyze monitoring data for wetland-dependent species in need of conservation attention. We maintain a network of shallow wells called piezometers in Snake Valley and Tule Valley to monitor groundwater discharge in key habitat for least chub and Columbia spotted frog. We also worked to help manage habitat data for the boreal toad with biologists from the Utah Division of Wildlife Resources, the U.S. Forest Service, and several non-profit-led citizen scientist organizations. During field surveys, we document any sensitive species we see and share that data with biologists, focusing on plants, amphibians, and mollusks.

### How Urgent is this?

Low

**Comment by Mackenzie-Cope** [comment]
Reviewed and updated on the website.
